version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --stage dev -v
  post_build:
    commands:
      - serverless remove --stage test -v